version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - jasongdove
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: daily
    assignees:
      - jasongdove
  - package-ecosystem: docker
    directory: "/docker/nvidia"
    schedule:
      interval: daily
    assignees:
      - jasongdove
  - package-ecosystem: docker
    directory: "/docker/vaapi"
    schedule:
      interval: daily
    assignees:
      - jasongdove
