version: "3.1"

services:
    ersatztv:
        build:
            context: .
            args:
                INFO_VERSION: "docker-compose-develop"
        ports:
            - "8409:8409"
        volumes:
            - ersatztv:/root/.local/share/ersatztv
            #- /media/shared:/media/shared:ro 
# uncomment for nvenc support
#        environment:
#            NVIDIA_VISIBLE_DEVICES: all
#            NVIDIA_DRIVER_CAPABILITIES: all
#        deploy:
#            resources:
#                reservations:
#                    devices:
#                        -   capabilities: [ gpu ]
volumes:
    ersatztv:
