//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainLayout {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLayout() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Shared.MainLayout", typeof(MainLayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonChannels {
            get {
                return ResourceManager.GetString("ButtonChannels", resourceCulture);
            }
        }
        
        internal static string ButtonFFmpegProfiles {
            get {
                return ResourceManager.GetString("ButtonFFmpegProfiles", resourceCulture);
            }
        }
        
        internal static string ButtonWatermarks {
            get {
                return ResourceManager.GetString("ButtonWatermarks", resourceCulture);
            }
        }
        
        internal static string ButtonMediaSources {
            get {
                return ResourceManager.GetString("ButtonMediaSources", resourceCulture);
            }
        }
        
        internal static string ButtonMedia {
            get {
                return ResourceManager.GetString("ButtonMedia", resourceCulture);
            }
        }
        
        internal static string ButtonLists {
            get {
                return ResourceManager.GetString("ButtonLists", resourceCulture);
            }
        }
        
        internal static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        internal static string ButtonMediaSourcesLocal {
            get {
                return ResourceManager.GetString("ButtonMediaSourcesLocal", resourceCulture);
            }
        }
        
        internal static string ButtonMediaSourcesEmby {
            get {
                return ResourceManager.GetString("ButtonMediaSourcesEmby", resourceCulture);
            }
        }
        
        internal static string ButtonMediaSourcesJellyfin {
            get {
                return ResourceManager.GetString("ButtonMediaSourcesJellyfin", resourceCulture);
            }
        }
        
        internal static string ButtonMediaSourcesPlex {
            get {
                return ResourceManager.GetString("ButtonMediaSourcesPlex", resourceCulture);
            }
        }
        
        internal static string ButtonMediaLibraries {
            get {
                return ResourceManager.GetString("ButtonMediaLibraries", resourceCulture);
            }
        }
        
        internal static string ButtonMediaTrash {
            get {
                return ResourceManager.GetString("ButtonMediaTrash", resourceCulture);
            }
        }
        
        internal static string ButtonMediaTvShows {
            get {
                return ResourceManager.GetString("ButtonMediaTvShows", resourceCulture);
            }
        }
        
        internal static string ButtonMediaMovies {
            get {
                return ResourceManager.GetString("ButtonMediaMovies", resourceCulture);
            }
        }
        
        internal static string ButtonMediaMusic {
            get {
                return ResourceManager.GetString("ButtonMediaMusic", resourceCulture);
            }
        }
        
        internal static string ButtonMediaOtherVideos {
            get {
                return ResourceManager.GetString("ButtonMediaOtherVideos", resourceCulture);
            }
        }
        
        internal static string ButtonMediaSongs {
            get {
                return ResourceManager.GetString("ButtonMediaSongs", resourceCulture);
            }
        }
        
        internal static string ButtonMediaImages {
            get {
                return ResourceManager.GetString("ButtonMediaImages", resourceCulture);
            }
        }
        
        internal static string ButtonMediaRemoteStreams {
            get {
                return ResourceManager.GetString("ButtonMediaRemoteStreams", resourceCulture);
            }
        }
        
        internal static string ButtonListsManualCollections {
            get {
                return ResourceManager.GetString("ButtonListsManualCollections", resourceCulture);
            }
        }
        
        internal static string ButtonListsSmartCollections {
            get {
                return ResourceManager.GetString("ButtonListsSmartCollections", resourceCulture);
            }
        }
        
        internal static string ButtonListsMultiCollections {
            get {
                return ResourceManager.GetString("ButtonListsMultiCollections", resourceCulture);
            }
        }
        
        internal static string ButtonListsRerunCollections {
            get {
                return ResourceManager.GetString("ButtonListsRerunCollections", resourceCulture);
            }
        }
        
        internal static string ButtonListsPlaylists {
            get {
                return ResourceManager.GetString("ButtonListsPlaylists", resourceCulture);
            }
        }
        
        internal static string ButtonListsTraktLists {
            get {
                return ResourceManager.GetString("ButtonListsTraktLists", resourceCulture);
            }
        }
        
        internal static string ButtonListsFillerPresets {
            get {
                return ResourceManager.GetString("ButtonListsFillerPresets", resourceCulture);
            }
        }
        
        internal static string ButtonScheduling {
            get {
                return ResourceManager.GetString("ButtonScheduling", resourceCulture);
            }
        }
        
        internal static string ButtonSchedulingSchedules {
            get {
                return ResourceManager.GetString("ButtonSchedulingSchedules", resourceCulture);
            }
        }
        
        internal static string ButtonSchedulingBlocks {
            get {
                return ResourceManager.GetString("ButtonSchedulingBlocks", resourceCulture);
            }
        }
        
        internal static string ButtonSchedulingTemplates {
            get {
                return ResourceManager.GetString("ButtonSchedulingTemplates", resourceCulture);
            }
        }
        
        internal static string ButtonSchedulingDecos {
            get {
                return ResourceManager.GetString("ButtonSchedulingDecos", resourceCulture);
            }
        }
        
        internal static string ButtonSchedulingDecoTemplates {
            get {
                return ResourceManager.GetString("ButtonSchedulingDecoTemplates", resourceCulture);
            }
        }
        
        internal static string ButtonSchedulingPlayouts {
            get {
                return ResourceManager.GetString("ButtonSchedulingPlayouts", resourceCulture);
            }
        }
        
        internal static string ButtonSettingsFFmpeg {
            get {
                return ResourceManager.GetString("ButtonSettingsFFmpeg", resourceCulture);
            }
        }
        
        internal static string ButtonSettingsLogging {
            get {
                return ResourceManager.GetString("ButtonSettingsLogging", resourceCulture);
            }
        }
        
        internal static string ButtonSettingsHdHomeRun {
            get {
                return ResourceManager.GetString("ButtonSettingsHdHomeRun", resourceCulture);
            }
        }
        
        internal static string ButtonSettingsScanner {
            get {
                return ResourceManager.GetString("ButtonSettingsScanner", resourceCulture);
            }
        }
        
        internal static string ButtonSettingsPlayout {
            get {
                return ResourceManager.GetString("ButtonSettingsPlayout", resourceCulture);
            }
        }
        
        internal static string ButtonSettingsUi {
            get {
                return ResourceManager.GetString("ButtonSettingsUi", resourceCulture);
            }
        }
        
        internal static string ButtonSettingsXmltv {
            get {
                return ResourceManager.GetString("ButtonSettingsXmltv", resourceCulture);
            }
        }
        
        internal static string ButtonSupport {
            get {
                return ResourceManager.GetString("ButtonSupport", resourceCulture);
            }
        }
        
        internal static string ButtonSupportHealthChecks {
            get {
                return ResourceManager.GetString("ButtonSupportHealthChecks", resourceCulture);
            }
        }
        
        internal static string ButtonSupportLogs {
            get {
                return ResourceManager.GetString("ButtonSupportLogs", resourceCulture);
            }
        }
        
        internal static string ButtonSupportTroubleshooting {
            get {
                return ResourceManager.GetString("ButtonSupportTroubleshooting", resourceCulture);
            }
        }
        
        internal static string LabelErsatzTVVersion {
            get {
                return ResourceManager.GetString("LabelErsatzTVVersion", resourceCulture);
            }
        }
        
        internal static string LabelSearchTargetChannel {
            get {
                return ResourceManager.GetString("LabelSearchTargetChannel", resourceCulture);
            }
        }
        
        internal static string LabelSearchTargetFFmpegProfile {
            get {
                return ResourceManager.GetString("LabelSearchTargetFFmpegProfile", resourceCulture);
            }
        }
        
        internal static string LabelSearchTargetChannelWatermark {
            get {
                return ResourceManager.GetString("LabelSearchTargetChannelWatermark", resourceCulture);
            }
        }
        
        internal static string LabelSearchTargetCollection {
            get {
                return ResourceManager.GetString("LabelSearchTargetCollection", resourceCulture);
            }
        }
        
        internal static string LabelSearchTargetMultiCollection {
            get {
                return ResourceManager.GetString("LabelSearchTargetMultiCollection", resourceCulture);
            }
        }
        
        internal static string LabelSearchTargetSmartCollection {
            get {
                return ResourceManager.GetString("LabelSearchTargetSmartCollection", resourceCulture);
            }
        }
        
        internal static string LabelSearchTargetSchedule {
            get {
                return ResourceManager.GetString("LabelSearchTargetSchedule", resourceCulture);
            }
        }
        
        internal static string LabelSearchTargetScheduleItems {
            get {
                return ResourceManager.GetString("LabelSearchTargetScheduleItems", resourceCulture);
            }
        }
        
        internal static string ButtonM3U {
            get {
                return ResourceManager.GetString("ButtonM3U", resourceCulture);
            }
        }
        
        internal static string ButtonXmltv {
            get {
                return ResourceManager.GetString("ButtonXmltv", resourceCulture);
            }
        }
        
        internal static string ButtonApi {
            get {
                return ResourceManager.GetString("ButtonApi", resourceCulture);
            }
        }
        
        internal static string ButtonDocumentation {
            get {
                return ResourceManager.GetString("ButtonDocumentation", resourceCulture);
            }
        }
        
        internal static string ButtonGitHub {
            get {
                return ResourceManager.GetString("ButtonGitHub", resourceCulture);
            }
        }
        
        internal static string ButtonLogout {
            get {
                return ResourceManager.GetString("ButtonLogout", resourceCulture);
            }
        }
        
        internal static string ButtonContact {
            get {
                return ResourceManager.GetString("ButtonContact", resourceCulture);
            }
        }
    }
}
