version: "3.1"

services:
    ersatztv:
        privileged: true
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [ gpu ]
