version: "3.1"

services:
    ersatztv:
        build:
            context: ..
            dockerfile: docker/nvidia/Dockerfile
        environment:
            NVIDIA_VISIBLE_DEVICES: all
            NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
        deploy:
            resources:
                reservations:
                    devices:
                        -   capabilities: [ gpu ]
