services:
    ersatztv:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                INFO_VERSION: "docker-compose-develop"
        environment:
            TZ: America/Chicago
        ports:
            - "8409:8409"
        volumes:
            - ersatztv:/config
            #- /media/shared:/media/shared:ro
        tmpfs:
            - /transcode
volumes:
    ersatztv:
