//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Channels {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Channels() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Channels", typeof(Channels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddChannel {
            get {
                return ResourceManager.GetString("ButtonAddChannel", resourceCulture);
            }
        }
        
        internal static string ButtonEditChannelNumbers {
            get {
                return ResourceManager.GetString("ButtonEditChannelNumbers", resourceCulture);
            }
        }
        
        internal static string LabelChannels {
            get {
                return ResourceManager.GetString("LabelChannels", resourceCulture);
            }
        }
        
        internal static string ButtonShowDisabled {
            get {
                return ResourceManager.GetString("ButtonShowDisabled", resourceCulture);
            }
        }
        
        internal static string LabelNumber {
            get {
                return ResourceManager.GetString("LabelNumber", resourceCulture);
            }
        }
        
        internal static string LabelLogo {
            get {
                return ResourceManager.GetString("LabelLogo", resourceCulture);
            }
        }
        
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        internal static string LabelStreamingMode {
            get {
                return ResourceManager.GetString("LabelStreamingMode", resourceCulture);
            }
        }
        
        internal static string LabelFFmpegProfile {
            get {
                return ResourceManager.GetString("LabelFFmpegProfile", resourceCulture);
            }
        }
        
        internal static string LabelRowsPerPage {
            get {
                return ResourceManager.GetString("LabelRowsPerPage", resourceCulture);
            }
        }
        
        internal static string LabelChannelDisabledHelp {
            get {
                return ResourceManager.GetString("LabelChannelDisabledHelp", resourceCulture);
            }
        }
        
        internal static string LabelChannelHiddenHelp {
            get {
                return ResourceManager.GetString("LabelChannelHiddenHelp", resourceCulture);
            }
        }
        
        internal static string LabelChannelHiddenAbbreviation {
            get {
                return ResourceManager.GetString("LabelChannelHiddenAbbreviation", resourceCulture);
            }
        }
        
        internal static string LabelChannelDisabledAbbreviation {
            get {
                return ResourceManager.GetString("LabelChannelDisabledAbbreviation", resourceCulture);
            }
        }
        
        internal static string ButtonPreviewChannelHelp {
            get {
                return ResourceManager.GetString("ButtonPreviewChannelHelp", resourceCulture);
            }
        }
        
        internal static string ButtonPreviewChannelHelpNormalize {
            get {
                return ResourceManager.GetString("ButtonPreviewChannelHelpNormalize", resourceCulture);
            }
        }
        
        internal static string ButtonPreviewChannelHelpBrowser {
            get {
                return ResourceManager.GetString("ButtonPreviewChannelHelpBrowser", resourceCulture);
            }
        }
        
        internal static string ButtonPreviewChannelHelpSettings {
            get {
                return ResourceManager.GetString("ButtonPreviewChannelHelpSettings", resourceCulture);
            }
        }
        
        internal static string ButtonStopTranscodeHelp {
            get {
                return ResourceManager.GetString("ButtonStopTranscodeHelp", resourceCulture);
            }
        }
        
        internal static string ButtonEditChannelHelp {
            get {
                return ResourceManager.GetString("ButtonEditChannelHelp", resourceCulture);
            }
        }
        
        internal static string ButtonTroubleshootChannelHelp {
            get {
                return ResourceManager.GetString("ButtonTroubleshootChannelHelp", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteChannelHelp {
            get {
                return ResourceManager.GetString("ButtonDeleteChannelHelp", resourceCulture);
            }
        }
    }
}
